name: GitHub Validate Code
on:
  pull_request:
    types:
      - opened
    branches:
      - 'main'
    paths:
      - "mud/**"
      - "test/**"
jobs:
  Validate-Code:
    runs-on: ubuntu-latest
    steps:
      - run: pip3 install pylint
      - run: pylint mud --disable=C0301,C0114,C0116,W1514,C0103,E0401,W0613,E0402 --fail-under=10
      - run: pip3 install mypy
      - run: mypy mud --ignore-missing-imports
      - run: pip3 install pytest
      - run: coverage run -m pytest
      - run: coverage report --fail-under=75